title: Roshan Shrestha
logo: "/assets/img/Roshan.png?raw=true"
description: > 
  About:
  <br><br>
  I'm a data enthusiast with a deep passion for data analytics and machine learning. I possess a strong quantitative and analytical background in data analytics, data mining, database management, ETL process, and visualization. I'm currently obtaining a Master's degree in Data Science and Analytics to deepen my knowledge.
  <br><br>
  I'm proficient in Python, JAVA, R, SQL, Tableau, Microsoft Power BI, and SAS. I'm also engaged in self-learning new technologies and concepts. I'm looking to leverage my analytical skills to provide data-driven insights and convert them into actionable strategies.
  <br><br>
  <a href="https://www.linkedin.com/in/casirose">View My LinkedIn Profile</a> 
  
google_analytics: G-MXV4NM5VLN
theme: jekyll-theme-minimal 
